### ISSUE TITLE
Wrong package on pypi

### ISSUE THREAD

**Issue by PouyaEsmaili** [artscoop/django-approval#3]
Seems like when you install django-approval using `pip install django-approval`, the main package `approval` is not added to site-packages. However, I think the master branch is correct. Maybe a new push on pypi?

**Comment by artscoop** [comment]
You're absolutely right and it happened on another project I worked on recently. I made a change in pyproject.toml to use hatchling, and tried things in order to properly include the code packages. It ended up working properly (namespaces also), and I only recently noticed it did not work at all on other machines.

I'm looking at it, I'll hit you up when it's fixed. Thanks for the alert.

**Comment by artscoop** [comment]
I think I got it. Python packaging is an infamous nightmare, the issue was with:

- using hatchling (the wheel generated was empty but the tar.gz was ok)
- using setuptools (I had to use the default layout for anything to work)

Tell me if this looks fixed for you.

**Comment by PouyaEsmaili** [comment]
It's fixed. thanks.

**Comment by PouyaEsmaili** [comment]
I think you are still missing the templates directory on the package.

**Comment by artscoop** [comment]
For the record, I've just uploaded a new version on PyPI that fixes the templates folder and only displays warning in the admin if an object is not approved.
